apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-codeql
spec:
  description: | 
    This pipeline clones a git repo and runs codeql on it
    
  params:
  - name: github-url
    type: string
  - name: repository
    type: string

  workspaces:
  - name: shared-data
  - name: ssh-creds

  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    - name: ssh-directory
      workspace: ssh-creds
    params:
    - name: url
      value:
        git@$(params.github-url):$(params.repository).git
    - name: deleteExisting
      value: "true"
  - name: build-and-code-scan
    taskRef:
      name: codeql-build-task

    runAfter:
      - fetch-source

    params:
    - name: github-url
      value: $(params.github-url)

    - name: commit-sha
      value: $(tasks.fetch-source.results.commit)
        
    - name: repository
      value: $(params.repository)
      
    workspaces:
    - name: source
      workspace: shared-data
